
services:
    civitta-app:
        container_name: civitta-app
        build: 
            context: .
            dockerfile: CivittaTest.API/Dockerfile
        depends_on:
            - mssql
        environment:
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DBConnection=${DB_CONNECTION}
        ports:
            - "8080:80"

    mssql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
         - SA_PASSWORD=${SA_PASSWORD}
         - ACCEPT_EULA=Y
        ports:
          - "1433:1433"
        volumes:
          - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: